/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_jni_WinDataProtection */

#ifndef _Included_org_cryptomator_jni_WinDataProtection
#define _Included_org_cryptomator_jni_WinDataProtection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_jni_WinDataProtection
 * Method:    protect0
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_jni_WinDataProtection_protect0
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_cryptomator_jni_WinDataProtection
 * Method:    unprotect0
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cryptomator_jni_WinDataProtection_unprotect0
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif