/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_jni_MacLaunchServices */

#ifndef _Included_org_cryptomator_jni_MacLaunchServices
#define _Included_org_cryptomator_jni_MacLaunchServices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_jni_MacLaunchServices
 * Method:    isLoginItemEnabled0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacLaunchServices_isLoginItemEnabled0
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacLaunchServices
 * Method:    enableLoginItem0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacLaunchServices_enableLoginItem0
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacLaunchServices
 * Method:    disableLoginItem0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacLaunchServices_disableLoginItem0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
