/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_jni_MacApplicationUiAppearance */

#ifndef _Included_org_cryptomator_jni_MacApplicationUiAppearance
#define _Included_org_cryptomator_jni_MacApplicationUiAppearance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    getCurrentInterfaceStyle0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_getCurrentInterfaceStyle0
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    setToAqua0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_setToAqua0
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    setToDarkAqua0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_setToDarkAqua0
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    addListener0
 * Signature: (Lorg/cryptomator/jni/MacApplicationUiInterfaceThemeListener;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_addListener0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    removeListener0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_removeListener0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
