/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_jni_MacApplicationUiAppearance */

#ifndef _Included_org_cryptomator_jni_MacApplicationUiAppearance
#define _Included_org_cryptomator_jni_MacApplicationUiAppearance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    setToAqua0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_setToAqua0
  (JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacApplicationUiAppearance
 * Method:    setToDarkAqua0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacApplicationUiAppearance_setToDarkAqua0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
