/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_jni_MacApplicationUiState */

#ifndef _Included_org_cryptomator_jni_MacApplicationUiState
#define _Included_org_cryptomator_jni_MacApplicationUiState
/*
 * Class:     org_cryptomator_jni_MacApplicationUiState
 * Method:    transformToForegroundApplication0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacApplicationUiState_transformToForegroundApplication0(JNIEnv *, jobject);

/*
 * Class:     org_cryptomator_jni_MacApplicationUiState
 * Method:    transformToAgentApplication0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cryptomator_jni_MacApplicationUiState_transformToAgentApplication0(JNIEnv *, jobject);

#endif
