/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cryptomator_ui_jni_MacFunctions */

#ifndef _Included_org_cryptomator_ui_jni_MacFunctions
#define _Included_org_cryptomator_ui_jni_MacFunctions
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_cryptomator_ui_jni_MacFunctions
	 * Method:    transformToForegroundApplication0
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_org_cryptomator_ui_jni_MacFunctions_transformToForegroundApplication0
	(JNIEnv *, jobject);
	
	/*
	 * Class:     org_cryptomator_ui_jni_MacFunctions
	 * Method:    transformToAgentApplication0
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_org_cryptomator_ui_jni_MacFunctions_transformToAgentApplication0
	(JNIEnv *, jobject);
	
#ifdef __cplusplus
}
#endif
#endif
